//created on: May 17, 2020
package sbnz
import sbnz.SBNZbackendapp.facts.Zemljiste;
//list any import classes here.



//declare any global variables here




rule "Klasifikovanje zemljista kao slabo kiselo"

    when
        $z: Zemljiste( phVrednost >= 5.51 && phVrednost <= 6.5 , phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.SLABO_KISELO);
        update($z);

end

rule "Klasifikovanje zemljista kao slabo karbonatno"
    //include attributes such as "salience" here...
    when
        $z: Zemljiste( kalcijumKarbonat > 0, kalcijumKarbonat <= 5 , calcCategory == calcCategory.NA )
    then
        $z.setCalcCategory(Zemljiste.calcCategory.SLABO_KARBONATNO);
        update($z);

end
