//created on: May 17, 2020
package sbnz
import sbnz.SBNZbackendapp.facts.Zemljiste;
//list any import classes here.



//declare any global variables here




rule "Klasifikovanje zemljista kao slabo kiselo"

    when
        $z: Zemljiste( phVrednost >= 5.51 && phVrednost <= 6.5 , phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.SLABO_KISELO);
        update($z);

end

rule "Klasifikovanje zemljista kao alkalno"

    when
        $z: Zemljiste( phVrednost > 7.2, phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.ALKALNO);
        update($z);

end

rule "Klasifikovanje zemljista kao neutralno"

    when
        $z: Zemljiste( phVrednost >= 6.51 && phVrednost <= 7.2 , phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.NEUTRALNO);
        update($z);

end

rule "Klasifikovanje zemljista kao kiselo"

    when
        $z: Zemljiste( phVrednost >= 4.51 && phVrednost <= 5.5 , phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.KISELO);
        update($z);

end

rule "Klasifikovanje zemljista kao jako kiselo"

    when
        $z: Zemljiste( phVrednost <= 4.5 , phCategory == phCategory.NA )
    then
        $z.setPhCategory(Zemljiste.phCategory.JAKO_KISELO);
        update($z);

end

rule "Klasifikovanje zemljista kao slabo karbonatno"
    //include attributes such as "salience" here...
    when
        $z: Zemljiste( kalcijumKarbonat > 0, kalcijumKarbonat <= 5 , calcCategory == calcCategory.NA )
    then
        $z.setCalcCategory(Zemljiste.calcCategory.SLABO_KARBONATNO);
        update($z);

end

rule "Klasifikovanje zemljista kao beskarbonatno"
    //include attributes such as "salience" here...
    when
        $z: Zemljiste( kalcijumKarbonat == 0 , calcCategory == calcCategory.NA )
    then
        $z.setCalcCategory(Zemljiste.calcCategory.BESKARBONATNO);
        update($z);

end

rule "Klasifikovanje zemljista kao srenje karbonatno"
    //include attributes such as "salience" here...
    when
        $z: Zemljiste( kalcijumKarbonat > 5, kalcijumKarbonat <= 10 , calcCategory == calcCategory.NA )
    then
        $z.setCalcCategory(Zemljiste.calcCategory.SREDNJE_KARBONATNO);
        update($z);

end

rule "Klasifikovanje zemljista kao jako karbonatno"
    //include attributes such as "salience" here...
    when
        $z: Zemljiste( kalcijumKarbonat < 10 , calcCategory == calcCategory.NA )
    then
        $z.setCalcCategory(Zemljiste.calcCategory.JAKO_KARBONATNO);
        update($z);

end

rule "Jabuka"
	when
		$z: Zemljiste(phCategory == phCategory.SLABO_KISELO)
	then
		System.out.println("");
		System.out.println("Jabuka");
		System.out.println("");
		
end